# Generated by Django 4.1 on 2022-12-05 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateflashcard',
            name='nextReviewDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 14, 47, 38, 314810)),
        ),
    ]
