# Generated by Django 4.1 on 2022-12-07 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcard", "0003_alter_privateflashcard_nextreviewdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privateflashcard",
            name="nextReviewDate",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 7, 10, 37, 41, 875795)
            ),
        ),
    ]
