# Generated by Django 4.1.3 on 2022-12-08 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_alter_privateflashcard_nextreviewdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateflashcard',
            name='nextReviewDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 10, 34, 51, 720808)),
        ),
    ]
