# Generated by Django 4.1.3 on 2022-12-08 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0006_alter_privateflashcard_nextreviewdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateflashcard',
            name='nextReviewDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 22, 22, 29, 537993)),
        ),
    ]
