# Generated by Django 4.1.3 on 2022-12-03 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishPrivateDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isVerified', models.BooleanField(default=False)),
                ('private_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deck.privateflashcarddeck')),
                ('public_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deck.publicflashcarddeck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
