# Generated by Django 4.1.3 on 2022-12-08 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0002_publishprivatedeck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishprivatedeck',
            name='public_deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deck.publicflashcarddeck'),
        ),
    ]
